services:
  - type: web
    name: reportgenerator
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: HEADLESS
        value: "true"
    healthCheckPath: /

